### ISSUE TITLE
hello，Could you tell me this support mac os M1? 

### ISSUE THREAD

**Issue by XinXin55** [gographics/imagick#324] opened 2024-07-12 03:50 UTC
I'm running error on m1
ld: warning: ignoring file /opt/local/lib/libMagickCore-6.Q16.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_AcquireDrawInfo", referenced from:
      __cgo_8aa3db5525f0_Cfunc_AcquireDrawInfo in 000038.o
     (maybe you meant: __cgo_8aa3db5525f0_Cfunc_AcquireDrawInfo)

**Comment by justinfx** [comment] 2024-07-12 04:17
I can confirm that I've been able to build on my own macos M1 laptop. Your error implies that you have mixed architecture libraries installed on your machine. You probably installed an x86_64 version of ImageMagick from homebrew? Is it a brand new install or is it a carry over from an older laptop?

**Comment by XinXin55** [comment] 2024-07-12 06:08
which version is for M1 ,the version 7 ？

**Comment by justinfx** [comment] 2024-07-12 06:16
It's not specific to this library. v3 is for ImageMagick7, and v2 is ImageMagick6.

You need to install whatever ImageMagick library you want, but for arm64

**Comment by XinXin55** [comment] 2024-07-12 06:19
Now I use v2 in my code,Which ImageMagick version I should  install on my m1 mac os ?  the ImageMagick6  i installed,but i not works

**Comment by XinXin55** [comment] 2024-07-12 06:21
How could I install the arm64 version? could you help me

**Comment by justinfx** [comment] 2024-07-12 07:09
Installing ImageMagick on your computer is kind of beyond the scope of support for this Go binding library.
I suspect you need to fully uninstall ImageMagick and the dependencies from homebrew and then reinstall them so they end up as arm64.
If it downloads ImageMagick7, use v3 of this library.

**Comment by justinfx** [comment] 2024-07-15 05:34
Going to close this ticket since it is a bit out of scope for any more support through this binding library.

**Closed as completed by justinfx** 2024-07-15 05:34 UTC
