### ISSUE TITLE
imagick.v2 library installation error

### ISSUE THREAD

**Issue by russ666** [gographics/imagick#106] opened 2016-11-20 18:45 UTC
`apt-get install -y libmagick-dev libmagickwand-dev`
`go get -u gopkg.in/gographics/imagick.v2/imagick`
returns error
`could not determine kind of name for C.ScaleKernelInfo`

**Comment by justinfx** [comment] 2016-11-20 20:08
Which version of ImageMagick?

```
identify -version
```

Also, make sure your `pkg-config` points at the version you expect:

```
pkg-config --cflags MagickWand
```

**Comment by russ666** [comment] 2016-11-21 17:01
`Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-11-10`

`-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-
linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6`

**Comment by justinfx** [comment] 2016-11-21 19:09
I've just build and tested against 6.9.9-9 and I can reproduce this. Must have overlooked this min version check when introducing the recent support for the Kernel API. I will figure out when this constant was introduced and fix the constants.

**Comment by justinfx** [comment] 2016-11-22 01:46
Ok it looks like ImageMagick introduced `ScaleKernelInfo` in 6.9.4-0 by moving it from a private to a public header, even though all of the definitions have been there in 6.8.9-9. This is one of those annoying aspects of trying to maintain binding compatibility with a range of versions, even when they are adding and removing symbols here and there over minor releases.

I've tested the approach of adding an extern C declaration of `ScaleKernelInfo` in the `kernel_info.go` file, which makes that private `ScaleKernelInfo` visible to Go when using ImageMagick 6.8.9-9 - 6.9.3-10. 

I can push up a merge tonight.

**Comment by russ666** [comment] 2016-11-22 07:31
looks good, thank you

**Comment by justinfx** [comment] 2016-11-22 21:38
Could you give this branch a test (`106_ScaleKernelInfo`) and confirm that it fixes your issue?

**Comment by russ666** [comment] 2016-11-23 06:22
now it raise an error on build
```
/usr/lib/go-1.6/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lmagic
collect2: error: ld returned 1 exit status
```

**Comment by justinfx** [comment] 2016-11-23 09:30
I've tested that branch on both linux and osx, against multiple ImageMagick versions and I am not seeing that error. Are you sure this is related? Seems like `pkg-config` is supplying a bad link flag. Does your `pkg-config --libs MagickWand MagickCore` have something funky like "-lmagic" in the output?

**Comment by russ666** [comment] 2016-11-23 21:50
`pkg-config --libs MagickWand MagickCore`
returns
`-lMagickWand-6.Q16 -lMagickCore-6.Q16`
btw, its an `Ubuntu 16.04.1 LTS`

**Comment by justinfx** [comment] 2016-11-23 21:52
I've also tested on Ubuntu 16.04. I am not sure why you are getting those linker errors.

**Comment by russ666** [comment] 2016-11-27 13:57
Finally fixed. I had a typo in my init script. `apt install libmagick-dev` must be `apt install libmagic-dev`. Thanks for help your fixes

**Closed** 2016-11-27 18:12 UTC
Labels: bug
