### ISSUE TITLE
How to rotate a image?

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#105] opened 2016-11-16 03:24 UTC
Hi,

   I want to rotate a image 15°,how i can do ?Thank you very much.

**Comment by justinfx** [comment] 2016-11-16 03:54
Have you tried anything yet? Do you have code that is not working as expected?

Have you looked at the documentation yet, or the examples?

- https://godoc.org/gopkg.in/gographics/imagick.v2/imagick#MagickWand.RotateImage
- [examples/affine/main.go](https://github.com/gographics/imagick/blob/7a09f264f4c58b65cdf44f5f459a5da66ca9bc64/examples/affine/main.go)

**Comment by skyleelove** [comment] 2016-11-16 04:01
Hi,
 I tried to use RotateImage（）like this:

n := imagick.NewMagickWand()
		err := n.SetSize(2000, 2000)
		if err != nil {
			return err
		}
		err = n.SetResolution(2000, 2000)
		if err != nil {
			return err
		}
		pixel := imagick.NewPixelWand()
		pixel.SetColor("transparent")
		err = n.SetBackgroundColor(pixel)
		if err != nil {
			return err
		}
		n.SetFormat("png")
		for x := 0; x < int(n.GetImageWidth()); x += int(n.GetImageWidth()) >> 2 {
			for y := 0; y < int(n.GetImageHeight()); y += int(n.GetImageHeight()) >> 2 {
				n.CompositeImage(w.watermark, imagick.COMPOSITE_OP_ATOP, x, y)
			}
		}
		err = n.RotateImage(pixel, 15)
		fmt.Println(err)
		if err != nil {
			return err
		}
		if dest.GetFormat() == "png" {
			dest.CompositeImage(n, imagick.COMPOSITE_OP_ATOP, 0, 0)
		} else {

			dest.CompositeImage(n, imagick.COMPOSITE_OP_BLEND, 0, 0)
		}

but I get this err
ERROR_WAND: wand contains no images `MagickWand-4' @ error/magick-image.c/MagickRotateImage/9194

Could you give a example to show how to use RotateImage()
Thank you very much!

**Comment by justinfx** [comment] 2016-11-16 04:27
This error is telling you that at the time when you call `RotateImage()`, you magick wand has no images in it. Your code is not runnable so I had to just simplify it into something that doesn't error:

```go
n := imagick.NewMagickWand()

pixel := imagick.NewPixelWand()
pixel.SetColor("transparent")

n.NewImage(2000, 2000, pixel)

if err := n.RotateImage(pixel, 15); err != nil {
    panic(err)
}
```

Basically, the problem is not with the call to `RotateImage`, but rather whatever you are doing with the wand before that point is not creating an image in the wand.

**Comment by justinfx** [comment] 2016-11-29 01:58
Closing since I believe your question has been answered.

**Closed by justinfx** 2016-11-29 01:58 UTC
Labels: question
