### ISSUE TITLE
Install imagick error in mac osx

### ISSUE THREAD

**Issue by EricYT** [gographics/imagick#34] opened 2015-05-24 01:27 UTC
When I installed the imagick in osx,I got these errors.Thanks for you help.
```c++
eric:go yutao$ go get github.com/gographics/imagick/imagick
# github.com/gographics/imagick/imagick
gcc did not produce error at completed:1
on input:
#line 7 "/Users/yutao/Documents/go/src/github.com/gographics/imagick/imagick/channel_type.go"

#include <wand/MagickWand.h>


#include <stddef.h> /* for ptrdiff_t and size_t below */

/* Define intgo when compiling with GCC.  */
typedef ptrdiff_t intgo;

typedef struct { char *p; intgo n; } _GoString_;
typedef struct { char *p; intgo n; intgo c; } _GoBytes_;
_GoString_ GoString(char *p);
_GoString_ GoStringN(char *p, int l);
_GoBytes_ GoBytes(void *p, int n);
char *CString(_GoString_);
void *_CMalloc(size_t);
#line 1 "not-declared"
void __cgo_f_1_1(void) { __typeof__(AllChannels) *__cgo_undefined__; }
#line 1 "not-type"
void __cgo_f_1_2(void) { AllChannels *__cgo_undefined__; }
#line 1 "not-const"
void __cgo_f_1_3(void) { enum { __cgo__undefined__ = (AllChannels)*1 }; }
#line 2 "not-declared"
void __cgo_f_2_1(void) { __typeof__(AlphaChannel) *__cgo_undefined__; }
#line 2 "not-type"
void __cgo_f_2_2(void) { AlphaChannel *__cgo_undefined__; }
#line 2 "not-const"
void __cgo_f_2_3(void) { enum { __cgo__undefined__ = (AlphaChannel)*1 }; }
#line 3 "not-declared"
void __cgo_f_3_1(void) { __typeof__(BlackChannel) *__cgo_undefined__; }
#line 3 "not-type"
void __cgo_f_3_2(void) { BlackChannel *__cgo_undefined__; }
#line 3 "not-const"
void __cgo_f_3_3(void) { enum { __cgo__undefined__ = (BlackChannel)*1 }; }
#line 4 "not-declared"
void __cgo_f_4_1(void) { __typeof__(BlueChannel) *__cgo_undefined__; }
#line 4 "not-type"
void __cgo_f_4_2(void) { BlueChannel *__cgo_undefined__; }
#line 4 "not-const"
void __cgo_f_4_3(void) { enum { __cgo__undefined__ = (BlueChannel)*1 }; }
#line 5 "not-declared"
void __cgo_f_5_1(void) { __typeof__(CompositeChannels) *__cgo_undefined__; }
#line 5 "not-type"
void __cgo_f_5_2(void) { CompositeChannels *__cgo_undefined__; }
#line 5 "not-const"
void __cgo_f_5_3(void) { enum { __cgo__undefined__ = (CompositeChannels)*1 }; }
#line 6 "not-declared"
void __cgo_f_6_1(void) { __typeof__(CyanChannel) *__cgo_undefined__; }
#line 6 "not-type"
void __cgo_f_6_2(void) { CyanChannel *__cgo_undefined__; }
#line 6 "not-const"
void __cgo_f_6_3(void) { enum { __cgo__undefined__ = (CyanChannel)*1 }; }
#line 7 "not-declared"
void __cgo_f_7_1(void) { __typeof__(DefaultChannels) *__cgo_undefined__; }
#line 7 "not-type"
void __cgo_f_7_2(void) { DefaultChannels *__cgo_undefined__; }
#line 7 "not-const"
void __cgo_f_7_3(void) { enum { __cgo__undefined__ = (DefaultChannels)*1 }; }
#line 8 "not-declared"
void __cgo_f_8_1(void) { __typeof__(GrayChannel) *__cgo_undefined__; }
#line 8 "not-type"
void __cgo_f_8_2(void) { GrayChannel *__cgo_undefined__; }
#line 8 "not-const"
void __cgo_f_8_3(void) { enum { __cgo__undefined__ = (GrayChannel)*1 }; }
#line 9 "not-declared"
void __cgo_f_9_1(void) { __typeof__(GrayChannels) *__cgo_undefined__; }
#line 9 "not-type"
void __cgo_f_9_2(void) { GrayChannels *__cgo_undefined__; }
#line 9 "not-const"
void __cgo_f_9_3(void) { enum { __cgo__undefined__ = (GrayChannels)*1 }; }
#line 10 "not-declared"
void __cgo_f_10_1(void) { __typeof__(GreenChannel) *__cgo_undefined__; }
#line 10 "not-type"
void __cgo_f_10_2(void) { GreenChannel *__cgo_undefined__; }
#line 10 "not-const"
void __cgo_f_10_3(void) { enum { __cgo__undefined__ = (GreenChannel)*1 }; }
#line 11 "not-declared"
void __cgo_f_11_1(void) { __typeof__(IndexChannel) *__cgo_undefined__; }
#line 11 "not-type"
void __cgo_f_11_2(void) { IndexChannel *__cgo_undefined__; }
#line 11 "not-const"
void __cgo_f_11_3(void) { enum { __cgo__undefined__ = (IndexChannel)*1 }; }
#line 12 "not-declared"
void __cgo_f_12_1(void) { __typeof__(MagentaChannel) *__cgo_undefined__; }
#line 12 "not-type"
void __cgo_f_12_2(void) { MagentaChannel *__cgo_undefined__; }
#line 12 "not-const"
void __cgo_f_12_3(void) { enum { __cgo__undefined__ = (MagentaChannel)*1 }; }
#line 13 "not-declared"
void __cgo_f_13_1(void) { __typeof__(OpacityChannel) *__cgo_undefined__; }
#line 13 "not-type"
void __cgo_f_13_2(void) { OpacityChannel *__cgo_undefined__; }
#line 13 "not-const"
void __cgo_f_13_3(void) { enum { __cgo__undefined__ = (OpacityChannel)*1 }; }
#line 14 "not-declared"
void __cgo_f_14_1(void) { __typeof__(RGBChannels) *__cgo_undefined__; }
#line 14 "not-type"
void __cgo_f_14_2(void) { RGBChannels *__cgo_undefined__; }
#line 14 "not-const"
void __cgo_f_14_3(void) { enum { __cgo__undefined__ = (RGBChannels)*1 }; }
#line 15 "not-declared"
void __cgo_f_15_1(void) { __typeof__(RedChannel) *__cgo_undefined__; }
#line 15 "not-type"
void __cgo_f_15_2(void) { RedChannel *__cgo_undefined__; }
#line 15 "not-const"
void __cgo_f_15_3(void) { enum { __cgo__undefined__ = (RedChannel)*1 }; }
#line 16 "not-declared"
void __cgo_f_16_1(void) { __typeof__(SyncChannels) *__cgo_undefined__; }
#line 16 "not-type"
void __cgo_f_16_2(void) { SyncChannels *__cgo_undefined__; }
#line 16 "not-const"
void __cgo_f_16_3(void) { enum { __cgo__undefined__ = (SyncChannels)*1 }; }
#line 17 "not-declared"
void __cgo_f_17_1(void) { __typeof__(TrueAlphaChannel) *__cgo_undefined__; }
#line 17 "not-type"
void __cgo_f_17_2(void) { TrueAlphaChannel *__cgo_undefined__; }
#line 17 "not-const"
void __cgo_f_17_3(void) { enum { __cgo__undefined__ = (TrueAlphaChannel)*1 }; }
#line 18 "not-declared"
void __cgo_f_18_1(void) { __typeof__(UndefinedChannel) *__cgo_undefined__; }
#line 18 "not-type"
void __cgo_f_18_2(void) { UndefinedChannel *__cgo_undefined__; }
#line 18 "not-const"
void __cgo_f_18_3(void) { enum { __cgo__undefined__ = (UndefinedChannel)*1 }; }
#line 19 "not-declared"
void __cgo_f_19_1(void) { __typeof__(YellowChannel) *__cgo_undefined__; }
#line 19 "not-type"
void __cgo_f_19_2(void) { YellowChannel *__cgo_undefined__; }
#line 19 "not-const"
void __cgo_f_19_3(void) { enum { __cgo__undefined__ = (YellowChannel)*1 }; }
#line 1 "completed"
int __cgo__1 = __cgo__2;

full error output:
not-type:1:39: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_1_2(void) { AllChannels *__cgo_undefined__; }
                                      ^
not-type:2:40: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_2_2(void) { AlphaChannel *__cgo_undefined__; }
                                       ^
not-type:3:40: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_3_2(void) { BlackChannel *__cgo_undefined__; }
                                       ^
not-type:4:39: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_4_2(void) { BlueChannel *__cgo_undefined__; }
                                      ^
not-type:5:45: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_5_2(void) { CompositeChannels *__cgo_undefined__; }
                                            ^
not-type:6:39: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_6_2(void) { CyanChannel *__cgo_undefined__; }
                                      ^
not-type:7:43: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_7_2(void) { DefaultChannels *__cgo_undefined__; }
                                          ^
not-type:8:39: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_8_2(void) { GrayChannel *__cgo_undefined__; }
                                      ^
not-type:9:40: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_9_2(void) { GrayChannels *__cgo_undefined__; }
                                       ^
not-type:10:41: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_10_2(void) { GreenChannel *__cgo_undefined__; }
                                        ^
not-type:11:41: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_11_2(void) { IndexChannel *__cgo_undefined__; }
                                        ^
not-type:12:43: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_12_2(void) { MagentaChannel *__cgo_undefined__; }
                                          ^
not-type:13:43: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_13_2(void) { OpacityChannel *__cgo_undefined__; }
                                          ^
not-type:14:40: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_14_2(void) { RGBChannels *__cgo_undefined__; }
                                       ^
not-type:15:39: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_15_2(void) { RedChannel *__cgo_undefined__; }
                                      ^
not-type:16:41: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_16_2(void) { SyncChannels *__cgo_undefined__; }
                                        ^
not-type:17:45: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_17_2(void) { TrueAlphaChannel *__cgo_undefined__; }
                                            ^
not-type:18:45: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_18_2(void) { UndefinedChannel *__cgo_undefined__; }
                                            ^
not-type:19:42: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_19_2(void) { YellowChannel *__cgo_undefined__; }
                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by justinfx** [comment] 2015-05-24 01:32
What version of ImageMagick do you have installed? And does your pkg-config output find them?

**Comment by justinfx** [comment] 2015-05-24 01:33
Also, which version of go and gcc?

**Comment by EricYT** [comment] 2015-05-24 13:57
ImageMagick-6.8.5-10
go version go1.4.2 darwin/386
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by justinfx** [comment] 2015-05-25 00:56
What about the output of the following two commands?

```bash
pkg-config --cflags --libs MagickWand
```

```bash
identify -version
```

**Comment by EricYT** [comment] 2015-05-25 14:16
pkg-config --cflags --libs MagickWand 
-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/6.8.5-10/include/ImageMagick-6 -L/usr/local/Cellar/imagemagick/6.8.5-10/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16 

Version: ImageMagick 6.8.5-10 2015-05-24 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2013 ImageMagick Studio LLC
Features: DPC Modules
Delegates: bzlib freetype jng jpeg lzma png tiff xml zlib

**Comment by justinfx** [comment] 2015-07-24 21:28
Did you ever end up getting this to build? I am not sure exactly what the problem is

**Comment by justinfx** [comment] 2015-12-23 19:26
It looks like a similar issue over here: https://github.com/mattn/go-sqlite3/issues/198
In that issue, the fix was to set your compiler to use clang instead of gcc. 

```bash
$ export CC=clang
```

On my machine, my default compiler is clang:

```bash
$ go env CC
clang
```

I'm going to close this issue since it looks like a general cgo + osx issue as opposed to being specific to this project.

**Closed by justinfx** 2015-12-23 19:26 UTC
