### ISSUE TITLE
Question about process hanging?

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#108] opened 2016-11-24 09:04 UTC
Hi,

     When I use imagick I find that my process not release.
     I use the command "pstree -p ",that the process more and more.
     How can I do to release this process?

**Comment by justinfx** [comment] 2016-11-24 09:44
What do you mean when you say your process doesn't release? Meaning a
program you run that uses imagick isn't quitting when you expect it to?

Not sure why that would happen. You would need to post sample code that
reproduces the issues.

**Comment by skyleelove** [comment] 2016-11-24 09:48
func main() {
	imagick.Initialize()
	// Schedule cleanup
	//defer imagick.Terminate()     *******/here I note/
	var err error

	mw := imagick.NewMagickWand()

	err = mw.ReadImage("logo:")
	if err != nil {
		panic(err)
	}

	// Get original logo size
	width := mw.GetImageWidth()
	height := mw.GetImageHeight()

	// Calculate half the size
	hWidth := uint(width / 2)
	hHeight := uint(height / 2)

	// Resize the image using the Lanczos filter
	// The blur factor is a float, where > 1 is blurry, < 1 is sharp
	err = mw.ResizeImage(hWidth, hHeight, imagick.FILTER_LANCZOS, 1)
	if err != nil {
		panic(err)
	}

	// Set the compression quality to 95 (high quality = low compression)
	err = mw.SetImageCompressionQuality(95)
	if err != nil {
		panic(err)
	}

	err = mw.DisplayImage(os.Getenv("DISPLAY"))
	if err != nil {
		panic(err)
	}
}

**Comment by skyleelove** [comment] 2016-11-24 09:53
I note "defer imagick.Terminate()".Because if I use this function,it will get a err like this:

Memory allocation failed `No such file or directory' @ fatal/tiff.c/UnregisterTIFFImage/2382.

**Comment by skyleelove** [comment] 2016-11-24 09:54
imageMagick version:   ImageMagick-6.9.6-2

tiff version:    libtiff-devel-3.9.4-18.el6_8.x86_64
                       libtiff-3.9.4-18.el6_8.x86_64

**Comment by justinfx** [comment] 2016-11-24 20:24
I ran this code you provided and it does exactly what I expect it to do. The `DisplayImage()` call blocks while it pops up the image in a viewer. If I close that window, the process then exits.

Is this the behaviour you are seeing? What are you expecting to happen?

**Comment by skyleelove** [comment] 2016-11-25 09:46
Hi，
  I see that when I give a request to my image server,I use the "gographics/imagick" to dispose the image, and I find that every request will new a precess after using the "gographics/imagick"(like ResizeImage()、CropImage()).And it is not GC.

                imagick.Initialize()
	        var imagePayload []byte
	        var err error
	        defer imagick.Terminate()
	        dest := imagick.NewMagickWand()
	        dest.ReadImageBlob(imagePath)
	        DestWidth := dest.GetImageWidth()
	       DestHight := dest.GetImageHeight()
	      err := this.CropImage(DestWidth, DestHight, dest)
			if err != nil {
				return nil, err
			}
			err = dest.SetFormat(image.Format)
			if err != nil {
				return nil, err
			}
              err = w.watermark.SetSize(2000, 2000)
			if err != nil {
				return err
			}
			err = w.watermark.SetResolution(2000, 2000)
			if err != nil {
				return err
			}
			pixel := imagick.NewPixelWand()
			pixel.SetColor("transparent")
			err = w.watermark.SetBackgroundColor(pixel)
			if err != nil {
				return err
			}
			pixel.Destroy()
                        err = w.watermark.ReadImage(markPath)
                        if err != nil {
                             fmt.Println(err)  
                       }
                       dest.CompositeImage(w.watermark, imagick.COMPOSITE_OP_ATOP, dx, dy)
                       w.watermark.Destroy()

**Comment by skyleelove** [comment] 2016-11-25 09:47
Hi,
    I give my part of code

**Comment by justinfx** [comment] 2016-11-25 10:06
Look I am not sure what is going on here. Your original question talked about a process hanging. I saw your usage of DisplayImage and it made sense for the process to block while the image is being displayed 

Now you have a new example that is completely different. And I see you are initialising and terminating imagick with each request which is a no no. 

I don't understand what you mean by "will new a precess". I apologize if there is a language barrier here, but I can't offer any help if the details don't make sense to me.

**Comment by justinfx** [comment] 2017-02-18 20:37
Closing because there is a lack of information about the problem

**Closed by justinfx** 2017-02-18 20:37 UTC
Labels: question
