### ISSUE TITLE
could not determine kind of name for C.ScaleKernelInfo

### ISSUE THREAD

**Issue by marusama** [gographics/imagick#109] opened 2016-11-28 16:41 UTC
Hello!
I updated this library to version 2.3.0 and got the error trying to build my project:
`16:06:08 [STDERR] # image_storage_api/vendor/gopkg.in/gographics/imagick.v2/imagick
16:06:08 [STDERR] could not determine kind of name for C.ScaleKernelInfo`

I think that the cause is https://github.com/gographics/imagick/pull/89
Please help to avoid this error. What prerequirements should I satisfy? Version 2.2.2 works well.

go version: 1.7.1
imagemagick version: 6.9.5.9-1
os:  centos 7

**Comment by justinfx** [comment] 2016-11-28 18:38
Its a duplicate of #106 but because of the multiple issues being raised in #106, it seems I had forgotten to actually merge the fix branch. I will do that today. 

Can you try the 106_ScaleKernelInfo branch? 
Your reported ImageMagick version doesn't look valid to me. There seem to be too many numbers. But if it is between versions 6.8.9 and 6.9.4, then you would be expected to hit this failure. If it is higher than that, then you should not be seeing it.

**Comment by justinfx** [comment] 2016-11-28 19:25
I've just merged `106_ScaleKernelInfo ` and tagged v2.3.1

**Comment by justinfx** [comment] 2016-11-29 01:58
If this issue still persists we can re-open this ticket with more details. But this is being closed as a dup of #106

**Closed by justinfx** 2016-11-29 01:58 UTC
Labels: bug

**Comment by marusama** [comment] 2016-11-29 10:02
2.3.1 works! Thank you!

**Comment by justinfx** [comment] 2016-11-29 10:27
Awesome! Thanks for confirming. I'm glad it wasn't an edge case that I had overlooked.
